---
all:
  hosts:
    mail.example.com:
  children:
    webservers:
      hosts:
        20.71.44.177:
      vars:
        ansible_python_interpreter: /usr/bin/python3              
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com:   