---
all:
  hosts:
    mail.example.com:
  children:
    webservers:
      hosts:
        20.71.236.70:
      vars:
        ansible_python_interpreter: /usr/bin/python3              
    dbservers:
      hosts:
        20.56.3.38:
      vars:
        ansible_python_interpreter: /usr/bin/python3  