# Création d'une App Service
---
- name: Création d'une App Service
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:
    # Creation du "resource group"
    - azure.azcollection.azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"

    # Creation d'un "App Service plan" & d'un "App Service"
    - azure.azcollection.azure_rm_webapp:
        resource_group: "{{ rg_name }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ rg_name }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "php"
            version: "7.2"