# Firewall
---
- name: Creation d'une Azure Database for MySQL
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:
    - azure.azcollection.azure_rm_resource:
        api_version: '2017-12-01'
        resource_group: "{{ rg_name }}"
        provider: dbformysql
        resource_type: servers
        resource_name: "{{ mysqlserver_name }}"
        subresource:
          - type: firewallrules
            name: externalaccess
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "255.255.255.255"