rg_name: RG_VMSS_Hosts
location: westeurope
vmss_name: Hosts
nbs_host: 3
admin_username: pierrc
vnet_name: Vnet_VM_Hosts
address_prefixes_cidr_vnet: 10.0.0.0/16
subnet_name: Subnet_VM_Hosts
address_prefix_cidr_subnet: 10.0.0.0/24
public_ip_web: IP-Pub
nsg_ssh_name: Nsg-SSH
vmss_lb_name: LB-00
vm_size: Standard_DS1_v2
offer_vm: UbuntuServer
publisher_vm: Canonical
sku_vm: 18.04-LTS
version_vm: latest
vault_name: KeyVaultPierrc
secret_name: PublicKey