---
- hosts: webservers
  remote_user: pierrc
  become: yes

  vars:
    user: pierrc

  tasks:
    - name: Mise à jour
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Installation des dépendances
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Installation de docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
    - name: Installation de docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Creation du repertoire "wordpress"
      file:
        path: /home/{{ user }}/wordpress
        state: directory
    
    - name: Copie du fichier docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/{{user}}/wordpress/docker-compose.yml

    - name: docker-compose du wordpress
      shell: docker-compose up -d
      args:
        chdir: /home/{{user}}/wordpress/
    

        
      
       