---
- hosts: webservers
  remote_user: pierrc
  become: yes

  tasks:

    - name: mise à jour
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes


- hosts: dbservers
  remote_user: pierrc
  become: yes

  tasks:

    - name: mise à jour
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes