- azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ rg_name }}"
    name: "{{ vnet_name }}"
    address_prefixes_cidr:
      - 10.0.0.0/8

- azure.azcollection.azure_rm_subnet:
    resource_group: "{{ rg_name }}"
    name: "{{ subnet_name }}"
    address_prefix_cidr: 10.240.0.0/16
    virtual_network_name: "{{ vnet_name }}"
  register: subnet     